import { describe, expect, it, vi } from "vitest";

import {
  buildDesktopV3AppShellGovernanceHelpText,
  runDesktopV3AppShellGovernanceCli,
} from "./verify-desktop-v3-app-shell-governance.mjs";

describe("verify-desktop-v3-app-shell-governance", () => {
  it("prints help without running verification", async () => {
    const logs = [];
    let invoked = false;

    const result = await runDesktopV3AppShellGovernanceCli({
      argv: ["--help"],
      collectViolationsImpl: async () => {
        invoked = true;
        return {
          appFiles: [],
          appProvidersProperties: [],
          appProvidersReferenceFiles: [],
          appProvidersSurface: [],
          appReferenceFiles: [],
          appShellReferenceFiles: [],
          appShellSurface: [],
          appSurface: [],
          initialRouteReferenceFiles: [],
          initialRouteSurface: [],
          initialRouteValues: [],
          layoutModeValues: [],
          navigationItemProperties: [],
          navigationItemsReferenceFiles: [],
          navigationItemsSurface: [],
          pageHeaderProperties: [],
          pageHeaderReferenceFiles: [],
          pageHeaderSurface: [],
          primaryNavigationHrefs: [],
          rendererReadyOptionProperties: [],
          rendererReadyReferenceFiles: [],
          rendererReadySurface: [],
          routeHandleProperties: [],
          routeHandleReferenceFiles: [],
          routeHandleSurface: [],
          routerIndexReferenceFiles: [],
          routerIndexSurface: [],
          routerPathSurface: [],
          routesReferenceFiles: [],
          routesSurface: [],
          scannedFileCount: 0,
          scannedFiles: [],
          secondaryNavigationHrefs: [],
          shellScaffoldProperties: [],
          shellScaffoldReferenceFiles: [],
          shellScaffoldSurface: [],
          sidebarProperties: [],
          sidebarReferenceFiles: [],
          sidebarSurface: [],
          themeProviderProperties: [],
          themeProviderReferenceFiles: [],
          themeProviderSurface: [],
          violations: [],
        };
      },
      consoleLogImpl: (message) => {
        logs.push(message);
      },
    });

    expect(result).toEqual({ help: true });
    expect(invoked).toBe(false);
    expect(logs).toEqual([buildDesktopV3AppShellGovernanceHelpText()]);
  });

  it("persists a passing summary before logging success", async () => {
    const config = {
      allowedAppExternalReferenceFiles: ["apps/desktop-v3/src/main.tsx"],
      allowedAppProvidersExternalReferenceFiles: ["apps/desktop-v3/src/app/App.tsx"],
      allowedAppProvidersProperties: ["children: ReactNode"],
      allowedAppProvidersSurface: ["fn:AppProviders"],
      allowedAppShellExternalReferenceFiles: ["apps/desktop-v3/src/app/router/routes.tsx"],
      allowedAppShellFiles: ["apps/desktop-v3/src/app/App.tsx"],
      allowedAppShellSurface: ["fn:AppShell"],
      allowedAppSurface: ["fn:App"],
      allowedInitialRouteExternalReferenceFiles: ["apps/desktop-v3/src/app/router/routes.tsx"],
      allowedInitialRouteSurface: ["fn:resolveDesktopV3InitialRoute"],
      allowedInitialRouteValues: ["/"],
      allowedLayoutModeValues: ["compact"],
      allowedNavigationItemProperties: ["href: string"],
      allowedNavigationItemsExternalReferenceFiles: ["apps/desktop-v3/src/app/layout/sidebar.tsx"],
      allowedNavigationItemsSurface: ["const:primaryNavigationItems"],
      allowedPageHeaderExternalReferenceFiles: ["apps/desktop-v3/src/app/layout/app-shell.tsx"],
      allowedPageHeaderProperties: ["title: string"],
      allowedPageHeaderSurface: ["fn:PageHeader"],
      allowedPrimaryNavigationHrefs: ["/"],
      allowedRendererReadyExternalReferenceFiles: ["apps/desktop-v3/src/main.tsx"],
      allowedRendererReadyOptionProperties: ["route?: string"],
      allowedRendererReadySurface: ["fn:reportDesktopV3RendererReady"],
      allowedRouteHandleExternalReferenceFiles: ["apps/desktop-v3/src/app/router/routes.tsx"],
      allowedRouteHandleProperties: ["title: string"],
      allowedRouteHandleSurface: ["interface:AppRouteHandle"],
      allowedRouterIndexExternalReferenceFiles: ["apps/desktop-v3/src/app/App.tsx"],
      allowedRouterIndexSurface: ["re-export:appRouter"],
      allowedRouterPathSurface: ["path:/"],
      allowedRoutesExternalReferenceFiles: ["apps/desktop-v3/src/app/router/index.tsx"],
      allowedRoutesSurface: ["const:appRouter"],
      allowedSecondaryNavigationHrefs: ["/preferences"],
      allowedShellScaffoldExternalReferenceFiles: ["apps/desktop-v3/src/app/layout/app-shell.tsx"],
      allowedShellScaffoldProperties: ["children: ReactNode"],
      allowedShellScaffoldSurface: ["fn:ShellScaffold"],
      allowedSidebarExternalReferenceFiles: ["apps/desktop-v3/src/app/layout/app-shell.tsx"],
      allowedSidebarProperties: ["width: number"],
      allowedSidebarSurface: ["fn:Sidebar"],
      allowedThemeProviderExternalReferenceFiles: ["apps/desktop-v3/src/app/providers/app-providers.tsx"],
      allowedThemeProviderProperties: ["children: ReactNode"],
      allowedThemeProviderSurface: ["fn:ThemeProvider"],
      latestSummaryPath: "/tmp/app-shell-governance/latest.json",
      outputDir: "/tmp/app-shell-governance",
      summaryPath: "/tmp/app-shell-governance/summary.json",
    };
    const consoleLogImpl = vi.fn();
    const collectViolationsImpl = vi.fn(async () => ({
      appFiles: ["apps/desktop-v3/src/app/App.tsx"],
      appProvidersProperties: ["children: ReactNode"],
      appProvidersReferenceFiles: ["apps/desktop-v3/src/app/App.tsx"],
      appProvidersSurface: ["fn:AppProviders"],
      appReferenceFiles: ["apps/desktop-v3/src/main.tsx"],
      appShellReferenceFiles: ["apps/desktop-v3/src/app/router/routes.tsx"],
      appShellSurface: ["fn:AppShell"],
      appSurface: ["fn:App"],
      initialRouteReferenceFiles: ["apps/desktop-v3/src/app/router/routes.tsx"],
      initialRouteSurface: ["fn:resolveDesktopV3InitialRoute"],
      initialRouteValues: ["/"],
      layoutModeValues: ["compact"],
      navigationItemProperties: ["href: string"],
      navigationItemsReferenceFiles: ["apps/desktop-v3/src/app/layout/sidebar.tsx"],
      navigationItemsSurface: ["const:primaryNavigationItems"],
      pageHeaderProperties: ["title: string"],
      pageHeaderReferenceFiles: ["apps/desktop-v3/src/app/layout/app-shell.tsx"],
      pageHeaderSurface: ["fn:PageHeader"],
      primaryNavigationHrefs: ["/"],
      rendererReadyOptionProperties: ["route?: string"],
      rendererReadyReferenceFiles: ["apps/desktop-v3/src/main.tsx"],
      rendererReadySurface: ["fn:reportDesktopV3RendererReady"],
      routeHandleProperties: ["title: string"],
      routeHandleReferenceFiles: ["apps/desktop-v3/src/app/router/routes.tsx"],
      routeHandleSurface: ["interface:AppRouteHandle"],
      routerIndexReferenceFiles: ["apps/desktop-v3/src/app/App.tsx"],
      routerIndexSurface: ["re-export:appRouter"],
      routerPathSurface: ["path:/"],
      routesReferenceFiles: ["apps/desktop-v3/src/app/router/index.tsx"],
      routesSurface: ["const:appRouter"],
      scannedFileCount: 3,
      scannedFiles: [
        "apps/desktop-v3/src/app/App.tsx",
        "apps/desktop-v3/src/app/router/index.tsx",
        "apps/desktop-v3/src/main.tsx",
      ],
      secondaryNavigationHrefs: ["/preferences"],
      shellScaffoldProperties: ["children: ReactNode"],
      shellScaffoldReferenceFiles: ["apps/desktop-v3/src/app/layout/app-shell.tsx"],
      shellScaffoldSurface: ["fn:ShellScaffold"],
      sidebarProperties: ["width: number"],
      sidebarReferenceFiles: ["apps/desktop-v3/src/app/layout/app-shell.tsx"],
      sidebarSurface: ["fn:Sidebar"],
      themeProviderProperties: ["children: ReactNode"],
      themeProviderReferenceFiles: ["apps/desktop-v3/src/app/providers/app-providers.tsx"],
      themeProviderSurface: ["fn:ThemeProvider"],
      violations: [],
    }));
    const createSummaryImpl = vi.fn(() => ({
      allowedAppExternalReferenceFiles: [...config.allowedAppExternalReferenceFiles],
      allowedAppProvidersExternalReferenceFiles: [...config.allowedAppProvidersExternalReferenceFiles],
      allowedAppProvidersProperties: [...config.allowedAppProvidersProperties],
      allowedAppProvidersSurface: [...config.allowedAppProvidersSurface],
      allowedAppShellExternalReferenceFiles: [...config.allowedAppShellExternalReferenceFiles],
      allowedAppShellFiles: [...config.allowedAppShellFiles],
      allowedAppShellSurface: [...config.allowedAppShellSurface],
      allowedAppSurface: [...config.allowedAppSurface],
      allowedInitialRouteExternalReferenceFiles: [...config.allowedInitialRouteExternalReferenceFiles],
      allowedInitialRouteSurface: [...config.allowedInitialRouteSurface],
      allowedInitialRouteValues: [...config.allowedInitialRouteValues],
      allowedLayoutModeValues: [...config.allowedLayoutModeValues],
      allowedNavigationItemProperties: [...config.allowedNavigationItemProperties],
      allowedNavigationItemsExternalReferenceFiles: [...config.allowedNavigationItemsExternalReferenceFiles],
      allowedNavigationItemsSurface: [...config.allowedNavigationItemsSurface],
      allowedPageHeaderExternalReferenceFiles: [...config.allowedPageHeaderExternalReferenceFiles],
      allowedPageHeaderProperties: [...config.allowedPageHeaderProperties],
      allowedPageHeaderSurface: [...config.allowedPageHeaderSurface],
      allowedPrimaryNavigationHrefs: [...config.allowedPrimaryNavigationHrefs],
      allowedRendererReadyExternalReferenceFiles: [...config.allowedRendererReadyExternalReferenceFiles],
      allowedRendererReadyOptionProperties: [...config.allowedRendererReadyOptionProperties],
      allowedRendererReadySurface: [...config.allowedRendererReadySurface],
      allowedRouteHandleExternalReferenceFiles: [...config.allowedRouteHandleExternalReferenceFiles],
      allowedRouteHandleProperties: [...config.allowedRouteHandleProperties],
      allowedRouteHandleSurface: [...config.allowedRouteHandleSurface],
      allowedRouterIndexExternalReferenceFiles: [...config.allowedRouterIndexExternalReferenceFiles],
      allowedRouterIndexSurface: [...config.allowedRouterIndexSurface],
      allowedRouterPathSurface: [...config.allowedRouterPathSurface],
      allowedRoutesExternalReferenceFiles: [...config.allowedRoutesExternalReferenceFiles],
      allowedRoutesSurface: [...config.allowedRoutesSurface],
      allowedSecondaryNavigationHrefs: [...config.allowedSecondaryNavigationHrefs],
      allowedShellScaffoldExternalReferenceFiles: [...config.allowedShellScaffoldExternalReferenceFiles],
      allowedShellScaffoldProperties: [...config.allowedShellScaffoldProperties],
      allowedShellScaffoldSurface: [...config.allowedShellScaffoldSurface],
      allowedSidebarExternalReferenceFiles: [...config.allowedSidebarExternalReferenceFiles],
      allowedSidebarProperties: [...config.allowedSidebarProperties],
      allowedSidebarSurface: [...config.allowedSidebarSurface],
      allowedThemeProviderExternalReferenceFiles: [...config.allowedThemeProviderExternalReferenceFiles],
      allowedThemeProviderProperties: [...config.allowedThemeProviderProperties],
      allowedThemeProviderSurface: [...config.allowedThemeProviderSurface],
      appFiles: [],
      appProvidersProperties: [],
      appProvidersReferenceFiles: [],
      appProvidersSurface: [],
      appReferenceFiles: [],
      appShellReferenceFiles: [],
      appShellSurface: [],
      appSurface: [],
      checkedAt: null,
      error: null,
      initialRouteReferenceFiles: [],
      initialRouteSurface: [],
      initialRouteValues: [],
      latestSummaryPath: config.latestSummaryPath,
      layoutModeValues: [],
      navigationItemProperties: [],
      navigationItemsReferenceFiles: [],
      navigationItemsSurface: [],
      outputDir: config.outputDir,
      pageHeaderProperties: [],
      pageHeaderReferenceFiles: [],
      pageHeaderSurface: [],
      primaryNavigationHrefs: [],
      rendererReadyOptionProperties: [],
      rendererReadyReferenceFiles: [],
      rendererReadySurface: [],
      routeHandleProperties: [],
      routeHandleReferenceFiles: [],
      routeHandleSurface: [],
      routerIndexReferenceFiles: [],
      routerIndexSurface: [],
      routerPathSurface: [],
      routesReferenceFiles: [],
      routesSurface: [],
      runId: "app-shell-governance-test",
      scannedFileCount: 0,
      scannedFiles: [],
      secondaryNavigationHrefs: [],
      shellScaffoldProperties: [],
      shellScaffoldReferenceFiles: [],
      shellScaffoldSurface: [],
      sidebarProperties: [],
      sidebarReferenceFiles: [],
      sidebarSurface: [],
      status: "running",
      summaryPath: config.summaryPath,
      themeProviderProperties: [],
      themeProviderReferenceFiles: [],
      themeProviderSurface: [],
      violationCount: 0,
      violations: [],
    }));
    const mkdirImpl = vi.fn(async () => {});
    const persistVerificationSummaryImpl = vi.fn(async () => {});
    const resolveConfigImpl = vi.fn(() => config);

    const result = await runDesktopV3AppShellGovernanceCli({
      argv: [],
      collectViolationsImpl,
      consoleLogImpl,
      createSummaryImpl,
      mkdirImpl,
      persistVerificationSummaryImpl,
      resolveConfigImpl,
      writeJsonFileImpl: vi.fn(async () => {}),
    });

    expect(result).toMatchObject({
      latestSummaryPath: config.latestSummaryPath,
      outputDir: config.outputDir,
      scannedFileCount: 3,
      status: "passed",
      summaryPath: config.summaryPath,
      violationCount: 0,
    });
    expect(resolveConfigImpl).toHaveBeenCalledOnce();
    expect(mkdirImpl).toHaveBeenCalledWith(config.outputDir, { recursive: true });
    expect(collectViolationsImpl).toHaveBeenCalledWith(config);
    expect(persistVerificationSummaryImpl).toHaveBeenCalledWith(
      expect.objectContaining({
        latestSummaryPath: config.latestSummaryPath,
        outputDir: config.outputDir,
        scannedFileCount: 3,
        summaryPath: config.summaryPath,
        violationCount: 0,
      }),
      {
        archiveSummaryPath: config.summaryPath,
        latestSummaryPath: config.latestSummaryPath,
      },
      {
        writeJsonFileImpl: expect.any(Function),
      },
    );
    expect(consoleLogImpl).toHaveBeenCalledWith(
      "desktop-v3 app shell governance passed. Summary: /tmp/app-shell-governance/summary.json | Latest: /tmp/app-shell-governance/latest.json",
    );
  });
});
